[package]
name = "whisper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
whisper-rs = "0.8.0"
hound = "3.5.0"
futures-util = "0.3.28"
